// Estructura de datos organizada por Grado y Test
const bibliotecaPalabras = {
    "1st Grade": {
        "Test 3": [
            { palabra: "cake", imagen: "./img/cake.jpg" },
            { palabra: "candy", imagen: "./img/candy.jpg" },
            { palabra: "carrot", imagen: "./img/carrot.jpg" },
            { palabra: "banana", imagen: "./img/banana.jpg" },
            { palabra: "chocolate", imagen: "./img/chocolate.jpg" },
            { palabra: "milk", imagen: "./img/milk.jpg" },
            { palabra: "water", imagen: "./img/water.jpg" },
            { palabra: "burger", imagen: "./img/burger.jpg" },
            { palabra: "lunch", imagen: "./img/lunch.jpg" },
            { palabra: "kiwi", imagen: "./img/kiwi.jpg" },
            { palabra: "lemon", imagen: "./img/lemon.jpg" },
            { palabra: "pie", imagen: "./img/pie.jpg" },
            { palabra: "mango", imagen: "./img/mango.jpg" },
            { palabra: "apple", imagen: "./img/apple.jpg" },
            { palabra: "arm", imagen: "./img/arm.jpg" },
            { palabra: "leg", imagen: "./img/leg.jpg" },
            { palabra: "nose", imagen: "./img/nose.jpg" },
            { palabra: "hand", imagen: "./img/hand.jpg" },
            { palabra: "mouth", imagen: "./img/mouth.jpg" },
            { palabra: "head", imagen: "./img/head.jpg" },
            { palabra: "eye", imagen: "./img/eye.jpg" },
            { palabra: "animal", imagen: "./img/animal.jpg" },
            { palabra: "bear", imagen: "./img/bear.jpg" },
            { palabra: "bee", imagen: "./img/bee.jpg" },
            { palabra: "bird", imagen: "./img/bird.jpg" },
            { palabra: "cat", imagen: "./img/cat.jpg" },
            { palabra: "chicken", imagen: "./img/chicken.jpg" },
            { palabra: "cow", imagen: "./img/cow.jpg" },
            { palabra: "dog", imagen: "./img/dog.jpg" },
            { palabra: "fish", imagen: "./img/fish.jpg" },
            { palabra: "pet", imagen: "./img/pet.jpg" },
            { palabra: "frog", imagen: "./img/frog.jpg" },
            { palabra: "tiger", imagen: "./img/tiger.jpg" },
            { palabra: "lizard", imagen: "./img/lizard.jpg" },
            { palabra: "hippo", imagen: "./img/hippo.jpg" },
            { palabra: "bag", imagen: "./img/bag.jpg" },
            { palabra: "hat", imagen: "./img/hat.jpg" },
            { palabra: "shoe", imagen: "./img/shoe.jpg" },
            { palabra: "skirt", imagen: "./img/skirt.jpg" },
            { palabra: "sock", imagen: "./img/sock.jpg" },
            { palabra: "boots", imagen: "./img/boots.jpg" },
            { palabra: "dress", imagen: "./img/dress.jpg" },
            { palabra: "red", imagen: "./img/red.jpg" },
            { palabra: "pink", imagen: "./img/pink.jpg" },
            { palabra: "blue", imagen: "./img/blue.jpg" },
            { palabra: "black", imagen: "./img/black.jpg" },
            { palabra: "orange", imagen: "./img/orange.jpg" },
            { palabra: "yellow", imagen: "./img/yellow.jpg" },
            { palabra: "brown", imagen: "./img/brown.jpg" },
            { palabra: "girl", imagen: "./img/girl.jpg" },
            { palabra: "mum", imagen: "./img/mum.jpg" },
            { palabra: "sister", imagen: "./img/sister.jpg" },
            { palabra: "family", imagen: "./img/family.jpg" },
            { palabra: "brother", imagen: "./img/brother.jpg" },
            { palabra: "baby", imagen: "./img/baby.jpg" },
            { palabra: "dad", imagen: "./img/dad.jpg" },
            { palabra: "door", imagen: "./img/door.jpg" },
            { palabra: "sofa", imagen: "./img/sofa.jpg" },
            { palabra: "bed", imagen: "./img/bed.jpg" },
            { palabra: "house", imagen: "./img/house.jpg" },
            { palabra: "lamp", imagen: "./img/lamp.jpg" },
            { palabra: "mat", imagen: "./img/mat.jpg" },
            { palabra: "mirror", imagen: "./img/mirror.jpg" },
            { palabra: "Alex", imagen: "./img/Alex.jpg" },
            { palabra: "Anna", imagen: "./img/Anna.jpg" },
            { palabra: "Ben", imagen: "./img/Ben.jpg" },
            { palabra: "Lucy", imagen: "./img/Lucy.jpg" },
            { palabra: "Kim", imagen: "./img/Kim.jpg" },
            { palabra: "Sam", imagen: "./img/Sam.jpg" },
            { palabra: "eraser", imagen: "./img/eraser.jpg" },
            { palabra: "letter", imagen: "./img/letter.jpg" },
            { palabra: "book", imagen: "./img/book.jpg" },
            { palabra: "class", imagen: "./img/class.jpg" },
            { palabra: "color", imagen: "./img/color.jpg" },
            { palabra: "crayon", imagen: "./img/crayon.jpg" },
            { palabra: "glue", imagen: "./img/glue.jpg" },
            { palabra: "mouse (computer)", imagen: "./img/mouse_computer.jpg" },
            { palabra: "number", imagen: "./img/number.jpg" },
            { palabra: "page", imagen: "./img/page.jpg" },
            { palabra: "pen", imagen: "./img/pen.jpg" },
            { palabra: "pencil", imagen: "./img/pencil.jpg" },
            { palabra: "school", imagen: "./img/school.jpg" },
            { palabra: "ruler", imagen: "./img/ruler.jpg" }
        ]
    },
    "3rd Grade": {
        "Test 3": [
            { palabra: "bookcase", imagen: "./img/bookcase.jpg" },
            { palabra: "cupboard", imagen: "./img/cupboard.jpg" },
            { palabra: "dining room", imagen: "./img/dining_room.jpg" },
            { palabra: "living room", imagen: "./img/living_room.jpg" },
            { palabra: "mirror", imagen: "./img/mirror.jpg" },
            { palabra: "television", imagen: "./img/television.jpg" },
            { palabra: "TV", imagen: "./img/TV.jpg" },
            { palabra: "wall", imagen: "./img/wall.jpg" },
            { palabra: "window", imagen: "./img/window.jpg" },
            { palabra: "rug", imagen: "./img/rug.jpg" },
            { palabra: "paper", imagen: "./img/paper.jpg" },
            { palabra: "Eva", imagen: "./img/Eva.jpg" },
            { palabra: "Grace", imagen: "./img/Grace.jpg" },
            { palabra: "Hugo", imagen: "./img/Hugo.jpg" },
            { palabra: "Jill", imagen: "./img/Jill.jpg" },
            { palabra: "May", imagen: "./img/May.jpg" },
            { palabra: "Nick", imagen: "./img/Nick.jpg" },
            { palabra: "Pat", imagen: "./img/Pat.jpg" },
            { palabra: "Sue", imagen: "./img/Sue.jpg" },
            { palabra: "thirteen", imagen: "./img/thirteen.jpg" },
            { palabra: "fourteen", imagen: "./img/fourteen.jpg" },
            { palabra: "fifteen", imagen: "./img/fifteen.jpg" },
            { palabra: "sixteen", imagen: "./img/sixteen.jpg" },
            { palabra: "seventeen", imagen: "./img/seventeen.jpg" },
            { palabra: "eighteen", imagen: "./img/eighteen.jpg" },
            { palabra: "nineteen", imagen: "./img/nineteen.jpg" },
            { palabra: "twenty", imagen: "./img/twenty.jpg" },
            { palabra: "here", imagen: "./img/here.jpg" },
            { palabra: "in front of", imagen: "./img/in_front_of.jpg" },
            { palabra: "playground", imagen: "./img/playground.jpg" },
            { palabra: "store", imagen: "./img/store.jpg" },
            { palabra: "street", imagen: "./img/street.jpg" },
            { palabra: "bookshop", imagen: "./img/bookshop.jpg" },
            { palabra: "alphabet", imagen: "./img/alphabet.jpg" },
            { palabra: "board", imagen: "./img/board.jpg" },
            { palabra: "classroom", imagen: "./img/classroom.jpg" },
            { palabra: "English", imagen: "./img/English.jpg" },
            { palabra: "eraser", imagen: "./img/eraser.jpg" },
            { palabra: "keyboard", imagen: "./img/keyboard.jpg" },
            { palabra: "rubber", imagen: "./img/rubber.jpg" },
            { palabra: "lesson", imagen: "./img/lesson.jpg" },
            { palabra: "jellyfish", imagen: "./img/jellyfish.jpg" },
            { palabra: "lizard", imagen: "./img/lizard.jpg" },
            { palabra: "mouse (mice)", imagen: "./img/mouse_mice.jpg" },
            { palabra: "polar bear", imagen: "./img/polar_bear.jpg" },
            { palabra: "sheep", imagen: "./img/sheep.jpg" },
            { palabra: "snake", imagen: "./img/snake.jpg" },
            { palabra: "spider", imagen: "./img/spider.jpg" },
            { palabra: "tail", imagen: "./img/tail.jpg" },
            { palabra: "tiger", imagen: "./img/tiger.jpg" },
            { palabra: "zebra", imagen: "./img/zebra.jpg" },
            { palabra: "zoo", imagen: "./img/zoo.jpg" },
            { palabra: "foot (feet)", imagen: "./img/foot_feet.jpg" },
            { palabra: "head", imagen: "./img/head.jpg" },
            { palabra: "smile", imagen: "./img/smile.jpg" },
            { palabra: "mouth", imagen: "./img/mouth.jpg" },
            { palabra: "hand", imagen: "./img/hand.jpg" },
            { palabra: "baseball cap", imagen: "./img/baseball_cap.jpg" },
            { palabra: "handbag", imagen: "./img/handbag.jpg" },
            { palabra: "shorts (clothes)", imagen: "./img/shorts_clothes.jpg" },
            { palabra: "trousers", imagen: "./img/trousers.jpg" },
            { palabra: "T-shirt", imagen: "./img/T-shirt.jpg" },
            { palabra: "wear", imagen: "./img/wear.jpg" },
            { palabra: "color (colour)", imagen: "./img/color_colour.jpg" },
            { palabra: "purple", imagen: "./img/purple.jpg" },
            { palabra: "white", imagen: "./img/white.jpg" },
            { palabra: "yellow", imagen: "./img/yellow.jpg" },
            { palabra: "child (children)", imagen: "./img/child_children.jpg" },
            { palabra: "classmate", imagen: "./img/classmate.jpg" },
            { palabra: "friend", imagen: "./img/friend.jpg" },
            { palabra: "grandfather", imagen: "./img/grandfather.jpg" },
            { palabra: "grandmother", imagen: "./img/grandmother.jpg" },
            { palabra: "man (men)", imagen: "./img/man_men.jpg" },
            { palabra: "old", imagen: "./img/old.jpg" },
            { palabra: "woman (women)", imagen: "./img/woman_women.jpg" },
            { palabra: "young", imagen: "./img/young.jpg" },
            { palabra: "bean", imagen: "./img/bean.jpg" },
            { palabra: "bread", imagen: "./img/bread.jpg" },
            { palabra: "breakfast", imagen: "./img/breakfast.jpg" },
            { palabra: "dinner", imagen: "./img/dinner.jpg" },
            { palabra: "grapes", imagen: "./img/grapes.jpg" },
            { palabra: "ice cream", imagen: "./img/ice_cream.jpg" },
            { palabra: "juice", imagen: "./img/juice.jpg" },
            { palabra: "meat", imagen: "./img/meat.jpg" },
            { palabra: "meatballs", imagen: "./img/meatballs.jpg" },
            { palabra: "pineapple", imagen: "./img/pineapple.jpg" },
            { palabra: "pea", imagen: "./img/pea.jpg" },
            { palabra: "sausage", imagen: "./img/sausage.jpg" },
            { palabra: "sweets", imagen: "./img/sweets.jpg" },
            { palabra: "apartment", imagen: "./img/apartment.jpg" },
            { palabra: "flat", imagen: "./img/flat.jpg" },
            { palabra: "arm", imagen: "./img/arm.jpg" },
            { palabra: "chair", imagen: "./img/chair.jpg" },
            { palabra: "bathroom", imagen: "./img/bathroom.jpg" },
            { palabra: "letter", imagen: "./img/letter.jpg" },
            { palabra: "line", imagen: "./img/line.jpg" },
            { palabra: "badminton", imagen: "./img/badminton.jpg" },
            { palabra: "bounce", imagen: "./img/bounce.jpg" },
            { palabra: "drawing", imagen: "./img/drawing.jpg" },
            { palabra: "fishing", imagen: "./img/fishing.jpg" },
            { palabra: "football", imagen: "./img/football.jpg" },
            { palabra: "skateboard", imagen: "./img/skateboard.jpg" },
            { palabra: "skateboarding", imagen: "./img/skateboarding.jpg" },
            { palabra: "table tennis", imagen: "./img/table_tennis.jpg" },
            { palabra: "take a picture", imagen: "./img/take_a_picture.jpg" },
            { palabra: "tennis racket", imagen: "./img/tennis_racket.jpg" },
            { palabra: "afternoon", imagen: "./img/afternoon.jpg" },
            { palabra: "evening", imagen: "./img/evening.jpg" },
            { palabra: "birthday", imagen: "./img/birthday.jpg" },
            { palabra: "alien", imagen: "./img/alien.jpg" },
            { palabra: "boardgame", imagen: "./img/boardgame.jpg" },
            { palabra: "helicopter", imagen: "./img/helicopter.jpg" },
            { palabra: "lorry (truck)", imagen: "./img/lorry_truck.jpg" },
            { palabra: "motorbike", imagen: "./img/motorbike.jpg" },
            { palabra: "teacher", imagen: "./img/teacher.jpg" },
            { palabra: "sea", imagen: "./img/sea.jpg" },
            { palabra: "beautiful", imagen: "./img/beautiful.jpg" },
            { palabra: "double", imagen: "./img/double.jpg" },
            { palabra: "fantastic", imagen: "./img/fantastic.jpg" },
            { palabra: "long", imagen: "./img/long.jpg" },
            { palabra: "new", imagen: "./img/new.jpg" },
            { palabra: "scary", imagen: "./img/scary.jpg" },
            { palabra: "silly", imagen: "./img/silly.jpg" },
            { palabra: "nice", imagen: "./img/nice.jpg" },
            { palabra: "a lot of", imagen: "./img/a_lot_of.jpg" },
            { palabra: "lots of", imagen: "./img/lots_of.jpg" },
            { palabra: "these", imagen: "./img/these.jpg" },
            { palabra: "those", imagen: "./img/those.jpg" },
            { palabra: "again", imagen: "./img/again.jpg" },
            { palabra: "now", imagen: "./img/now.jpg" },
            { palabra: "really", imagen: "./img/really.jpg" },
            { palabra: "about", imagen: "./img/about.jpg" },
            { palabra: "of", imagen: "./img/of.jpg" },
            { palabra: "but", imagen: "./img/but.jpg" }
        ]
    }
};

// Variable global que usará el juego (se llena al elegir en el menú)
let bancoDePalabras = [];